/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Kamaleonte Flutter Academy",
  "tagline": "Guía completa de desarrollo Flutter para nuevos desarrolladores en prácticas",
  "favicon": "img/flutter-icon.ico",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "url": "https://alejandrojimenezdiaz.github.io",
  "baseUrl": "/flutterFormacion/en/",
  "organizationName": "alejandrojimenezdiaz",
  "projectName": "flutterFormacion",
  "deploymentBranch": "gh-pages",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "es",
    "locales": [
      "es",
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/tu-usuario/flutter-guia-completa/tree/main/",
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": false,
          "includeCurrentVersion": true,
          "breadcrumbs": true,
          "remarkPlugins": [],
          "rehypePlugins": []
        },
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true,
            "copyright": "Copyright © 2025 Flutter Guía Completa"
          },
          "editUrl": "https://github.com/tu-usuario/flutter-guia-completa/tree/main/",
          "blogTitle": "Flutter Blog - Guía Completa",
          "blogDescription": "Tips, trucos y novedades de Flutter para desarrolladores",
          "postsPerPage": 10,
          "blogSidebarCount": 5,
          "blogSidebarTitle": "Posts Recientes",
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn",
          "tagsBasePath": "tags",
          "archiveBasePath": "archive"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "gtag": {
          "trackingID": "G-XXXXXXXXXX",
          "anonymizeIP": true
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-pwa",
      {
        "debug": true,
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "pwaHead": [
          {
            "tagName": "link",
            "rel": "icon",
            "href": "/img/flutter-icon.png"
          },
          {
            "tagName": "link",
            "rel": "manifest",
            "href": "/manifest.json"
          },
          {
            "tagName": "meta",
            "name": "theme-color",
            "content": "#02569B"
          }
        ]
      }
    ]
  ],
  "themeConfig": {
    "image": "img/flutter-social-card.png",
    "navbar": {
      "title": "Kamaleonte Academy",
      "logo": {
        "alt": "Kamaleonte Logo",
        "src": "img/kamaleonte-logo.svg",
        "srcDark": "img/kamaleonte-logo-dark.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "📚 Guía"
        },
        {
          "to": "/blog",
          "label": "📝 Blog",
          "position": "left"
        },
        {
          "to": "/progreso",
          "label": "📊 Mi Progreso",
          "position": "left"
        },
        {
          "type": "dropdown",
          "label": "🛠️ Herramientas",
          "position": "left",
          "items": [
            {
              "label": "⚙️ Configuración VS Code",
              "to": "/docs/entorno/vscode"
            },
            {
              "label": "🔍 Validador Flutter",
              "to": "/tools/validator"
            },
            {
              "label": "📦 Paquetes Recomendados",
              "href": "https://pub.dev"
            },
            {
              "label": "🎯 Plantillas de Proyecto",
              "href": "https://github.com/flutter/samples"
            }
          ]
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://github.com/tu-usuario/flutter-guia-completa",
          "className": "header-github-link",
          "aria-label": "GitHub repository",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "📚 Documentación",
          "items": [
            {
              "label": "🚀 Comenzar",
              "to": "/docs/intro"
            },
            {
              "label": "⚙️ Configuración",
              "to": "/docs/entorno/instalacion"
            },
            {
              "label": "📱 Despliegue",
              "to": "/docs/despliegue/google-play"
            }
          ]
        },
        {
          "title": "🌍 Comunidad Flutter",
          "items": [
            {
              "label": "Flutter.dev",
              "href": "https://flutter.dev"
            },
            {
              "label": "Pub.dev",
              "href": "https://pub.dev"
            },
            {
              "label": "Flutter Community",
              "href": "https://flutter.dev/community"
            }
          ]
        },
        {
          "title": "🔗 Recursos",
          "items": [
            {
              "label": "📝 Blog",
              "to": "/blog"
            },
            {
              "label": "💻 GitHub",
              "href": "https://github.com/tu-usuario/flutter-guia-completa"
            },
            {
              "label": "🎯 Ejemplos",
              "href": "https://github.com/flutter/samples"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Flutter Guía Completa. Construido con ❤️ y Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "dart",
        "yaml",
        "json",
        "bash"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "announcementBar": {
      "id": "flutter-launch",
      "content": "🚀 <b>¡Nueva guía disponible!</b> Aprende Flutter desde cero hasta producción. <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"/docs/intro\">¡Comenzar ahora!</a>",
      "backgroundColor": "#02569B",
      "textColor": "#ffffff",
      "isCloseable": true
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    },
    "metadata": []
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
